# Property Price Prediction

## Load the libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# skip warnings
import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings(action = 'ignore', category = DeprecationWarning)
warnings.filterwarnings(action = 'ignore', category = FutureWarning)

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)  
pd.set_option('display.expand_frame_repr',False)
pd.set_option('max_colwidth',-1)

## Read data

In [4]:
data = pd.read_csv('Property_Price.csv')

In [5]:
data.head()

   Id  Building_Class Zoning_Class  Lot_Extent  Lot_Size Road_Type Lane_Type Property_Shape Land_Outline Utility_Type Lot_Configuration Property_Slope Neighborhood Condition1 Condition2 House_Type House_Design  Overall_Material  House_Condition  Construction_Year  Remodel_Year Roof_Design Roof_Quality Exterior1st Exterior2nd Brick_Veneer_Type  Brick_Veneer_Area Exterior_Material Exterior_Condition Foundation_Type Basement_Height Basement_Condition Exposure_Level BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  Total_Basement_Area Heating_Type Heating_Quality Air_Conditioning Electrical_System  First_Floor_Area  Second_Floor_Area  LowQualFinSF  Grade_Living_Area  Underground_Full_Bathroom  Underground_Half_Bathroom  Full_Bathroom_Above_Grade  Half_Bathroom_Above_Grade  Bedroom_Above_Grade  Kitchen_Above_Grade Kitchen_Quality  Rooms_Above_Grade Functional_Rate  Fireplaces Fireplace_Quality  Garage  Garage_Built_Year Garage_Finish_Year  Garage_Size  Garage_Area Garage_Quality Garage_Condition Pavedd_Drive  W_Deck_Area  Open_Lobby_Area  Enclosed_Lobby_Area  Three_Season_Lobby_Area  Screen_Lobby_Area  Pool_Area Pool_Quality Fence_Quality Miscellaneous_Feature  Miscellaneous_Value  Month_Sold  Year_Sold Sale_Type Sale_Condition  Sale_Price
0  1   60              RLD          65.0        8450      Paved     NaN       Reg            Lvl          AllPub       I                 GS             CollgCr      Norm       Norm       1Fam       2Story       7                 5                2003               2003          Gable       SS           VinylSd     VinylSd     BrkFace           196.0              Gd                TA                 PC              Gd              TA                 No             GLQ          706         Unf          0           150        856                  GasA         Ex              Y                SBrkr             856               854                0             1710               1                          0                          2                          1                          3                    1                    Gd              8                  TF              0           NaN               Attchd  2003.0             RFn                2            1085.793744  TA             TA               Y            163.788080   69.596115        20.337934            0                        0                  0          NaN          NaN           NaN                   0                    2           2008       WD        Normal         208500
1  2   20              RLD          80.0        9600      Paved     NaN       Reg            Lvl          AllPub       FR2P              GS             Veenker      Feedr      Norm       1Fam       1Story       6                 8                1976               1976          Gable       SS           MetalSd     MetalSd     None              0.0                TA                TA                 CB              Gd              TA                 Gd             ALQ          978         Unf          0           284        1262                 GasA         Ex              Y                SBrkr             1262              0                  0             1262               0                          1                          2                          0                          3                    1                    TA              6                  TF              1           TA                Attchd  1976.0             RFn                2            196.316304   TA             TA               Y            198.900074   74.716033        15.039392            0                        0                  0          NaN          NaN           NaN                   0                    5           2007       WD        Normal         181500
2  3   60              RLD          68.0        11250     Paved     NaN       IR1            Lvl          AllPub       I                 GS             CollgCr      Norm       Norm       1Fam       2Story       7                 5                2001               2002          Gable       SS           VinylSd     VinylSd     BrkFace           162.0              Gd                TA                 PC              Gd              TA                 Mn             GLQ          486         Unf          0           434        920                  GasA         Ex              Y                SBrkr             920               866                0             1786               1                          0                          2                          1                          3                    1                    Gd              6                  TF              1           TA                Attchd  2001.0             RFn                2            218.068403   TA             TA               Y            26.127533    32.085268       -46.232198            0                        0                  0          NaN          NaN           NaN                   0                    9           2008       WD        Normal         223500
3  4   70              RLD          60.0        9550      Paved     NaN       IR1            Lvl          AllPub       C                 GS             Crawfor      Norm       Norm       1Fam       2Story       7                 5                1915               1970          Gable       SS           Wd Sdng     Wd Shng     None              0.0                TA                TA                 BT              TA              Gd                 No             ALQ          216         Unf          0           540        756                  GasA         Gd              Y                SBrkr             961               756                0             1717               1                          0                          1                          0                          3                    1                    Gd              7                  TF              1           Gd                Detchd  1998.0             Unf                3            696.996439   TA             TA               Y            46.948018    40.181415        60.921821            0                        0                  0          NaN          NaN           NaN                   0                    2           2006       WD        Abnorml        140000
4  5   60              RLD          84.0        14260     Paved     NaN       IR1            Lvl          AllPub       FR2P              GS             NoRidge      Norm       Norm       1Fam       2Story       8                 5                2000               2000          Gable       SS           VinylSd     VinylSd     BrkFace           350.0              Gd                TA                 PC              Gd              TA                 Av             GLQ          655         Unf          0           490        1145                 GasA         Ex              Y                SBrkr             1145              1053               0             2198               1                          0                          2                          1                          4                    1                    Gd              9                  TF              1           TA                Attchd  2000.0             RFn                3            568.859882   TA             TA               Y           -10.626105    20.755323        21.788818            0                        0                  0          NaN          NaN           NaN                   0                    12          2008       WD        Normal         250000

In [6]:
data.shape

(1459, 81)

In [7]:
data.Id.nunique()

1459

As all the values in this column are unique, we will **set Id as row index.**

In [8]:
data.set_index('Id', inplace = True)

In [13]:
data.describe().T

                            count           mean           std           min            25%            50%            75%            max
Building_Class             1459.0  56.922550      42.304033     20.000000     20.000000      50.000000      70.000000      190.000000
Lot_Extent                 1200.0  70.045833      24.294456     21.000000     59.000000      69.000000      80.000000      313.000000
Lot_Size                   1459.0  10517.225497   9984.675721   1300.000000   7549.000000    9477.000000    11603.000000   215245.000000
Overall_Material           1459.0  6.100069       1.383171      1.000000      5.000000       6.000000       7.000000       10.000000
House_Condition            1459.0  5.575051       1.113125      1.000000      5.000000       5.000000       6.000000       9.000000
Construction_Year          1459.0  1971.272104    30.212814     1872.000000   1954.000000    1973.000000    2000.000000    2010.000000
Remodel_Year               1459.0  1984.879369    20.645927     1950.000000   1967.000000    1994.000000    2004.000000    2010.000000
Brick_Veneer_Area          1451.0  103.756720     181.108150    0.000000      0.000000       0.000000       166.000000     1600.000000
BsmtFinSF1                 1459.0  443.374914     456.142186    0.000000      0.000000       383.000000     712.000000     5644.000000
BsmtFinSF2                 1459.0  46.382454      161.248500    0.000000      0.000000       0.000000       0.000000       1474.000000
BsmtUnfSF                  1459.0  567.535984     441.874057    0.000000      223.500000     479.000000     808.000000     2336.000000
Total_Basement_Area        1459.0  1057.293352    438.824912    0.000000      795.500000     991.000000     1298.500000    6110.000000
First_Floor_Area           1459.0  1162.562714    386.712553    334.000000    882.000000     1086.000000    1391.500000    4692.000000
Second_Floor_Area          1459.0  347.230295     436.583480    0.000000      0.000000       0.000000       728.000000     2065.000000
LowQualFinSF               1459.0  5.848526       48.639512     0.000000      0.000000       0.000000       0.000000       572.000000
Grade_Living_Area          1459.0  1515.641535    525.616607    334.000000    1129.000000    1464.000000    1777.500000    5642.000000
Underground_Full_Bathroom  1459.0  0.424949       0.518870      0.000000      0.000000       0.000000       1.000000       3.000000
Underground_Half_Bathroom  1459.0  0.057574       0.238830      0.000000      0.000000       0.000000       0.000000       2.000000
Full_Bathroom_Above_Grade  1459.0  1.565456       0.550906      0.000000      1.000000       2.000000       2.000000       3.000000
Half_Bathroom_Above_Grade  1459.0  0.382454       0.502798      0.000000      0.000000       0.000000       1.000000       2.000000
Bedroom_Above_Grade        1459.0  2.866347       0.816050      0.000000      2.000000       3.000000       3.000000       8.000000
Kitchen_Above_Grade        1459.0  1.046607       0.220410      0.000000      1.000000       1.000000       1.000000       3.000000
Rooms_Above_Grade          1459.0  6.518163       1.625894      2.000000      5.000000       6.000000       7.000000       14.000000
Fireplaces                 1459.0  0.613434       0.644687      0.000000      0.000000       1.000000       1.000000       3.000000
Garage_Built_Year          1378.0  1978.515965    24.696004     1900.000000   1961.000000    1980.000000    2002.000000    2010.000000
Garage_Size                1459.0  1.767649       0.747301      0.000000      1.000000       2.000000       2.000000       4.000000
Garage_Area                1459.0  470.934787     210.668787   -129.369350    329.290489     471.028116     607.184977     1147.488093
W_Deck_Area                1459.0  93.015667      124.796682   -338.112031    9.656026       92.803628      180.335986     572.298709
Open_Lobby_Area            1459.0  47.811902      67.467586    -187.149958    1.843186       46.837919      96.523486      255.362547
Enclosed_Lobby_Area        1459.0  24.580227      61.353507    -164.807386   -16.807302      25.026953      66.237591      225.762714
Three_Season_Lobby_Area    1459.0  3.411926       29.327247     0.000000      0.000000       0.000000       0.000000       508.000000
Screen_Lobby_Area          1459.0  15.071282      55.775138     0.000000      0.000000       0.000000       0.000000       480.000000
Pool_Area                  1459.0  2.760795       40.191018     0.000000      0.000000       0.000000       0.000000       738.000000
Miscellaneous_Value        1459.0  43.518849      496.291826    0.000000      0.000000       0.000000       0.000000       15500.000000
Month_Sold                 1459.0  6.322138       2.704540      1.000000      5.000000       6.000000       8.000000       12.000000
Year_Sold                  1459.0  2007.815627    1.328542      2006.000000   2007.000000    2008.000000    2009.000000    2010.000000
Sale_Price                 1459.0  180944.102810  79464.918335  34900.000000  129950.000000  163000.000000  214000.000000  755000.000000

**Observation:**
    
    The wide difference between min and max values tell us that we have few outliers in our data.
    
    we can also drop all those columns where 75% of our observations is zero.

## check for missing values

In [11]:
data.isnull().sum()

Building_Class               0
Zoning_Class                 0
Lot_Extent                   259
Lot_Size                     0
Road_Type                    0
Lane_Type                    1368
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Type            8
Brick_Veneer_Area            8
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Height              37
Basement_Condition           37
Exposure_Level               38
BsmtFinType1                 37
BsmtFinSF1                   0
BsmtFinType2                 38
BsmtFinSF2                   0
BsmtUnfSF                    0
Total_Basement_Area          0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            1
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Fireplace_Quality            689
Garage                       81
Garage_Built_Year            81
Garage_Finish_Year           81
Garage_Size                  0
Garage_Area                  0
Garage_Quality               81
Garage_Condition             81
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Pool_Quality                 1452
Fence_Quality                1178
Miscellaneous_Feature        1405
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

## Display only missing columns in percentage

In [14]:
missing = data.isnull().sum() *100 / len(data)
missing = missing [missing > 0]
missing.sort_values(inplace = True)
missing

Electrical_System        0.068540
Brick_Veneer_Type        0.548321
Brick_Veneer_Area        0.548321
Basement_Height          2.535984
Basement_Condition       2.535984
BsmtFinType1             2.535984
Exposure_Level           2.604524
BsmtFinType2             2.604524
Garage_Condition         5.551748
Garage_Quality           5.551748
Garage_Finish_Year       5.551748
Garage                   5.551748
Garage_Built_Year        5.551748
Lot_Extent               17.751885
Fireplace_Quality        47.224126
Fence_Quality            80.740233
Lane_Type                93.762851
Miscellaneous_Feature    96.298835
Pool_Quality             99.520219
dtype: float64

Dropping of those columns which has more than 45% of missing data

In [15]:
data.columns[data.isnull().sum()*100/data.shape[0] > 45]

Index(['Lane_Type', 'Fireplace_Quality', 'Pool_Quality', 'Fence_Quality',
       'Miscellaneous_Feature'],
      dtype='object')

In [16]:
data = data.drop(['Lane_Type', 'Fireplace_Quality', 'Pool_Quality', 'Fence_Quality',
                   'Miscellaneous_Feature'], axis = 1)

In [17]:
data.shape

(1459, 75)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 1 to 1459
Data columns (total 75 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Building_Class             1459 non-null   int64
 1   Zoning_Class               1459 non-null   object
 2   Lot_Extent                 1200 non-null   float64
 3   Lot_Size                   1459 non-null   int64
 4   Road_Type                  1459 non-null   object
 5   Property_Shape             1459 non-null   object
 6   Land_Outline               1459 non-null   object
 7   Utility_Type               1459 non-null   object
 8   Lot_Configuration          1459 non-null   object
 9   Property_Slope             1459 non-null   object
 10  Neighborhood               1459 non-null   object
 11  Condition1                 1459 non-null   object
 12  Condition2                 1459 non-null   object
 13  House_Type                 1459 non-null   object
 14  House_Design               1459 non-null   object
 15  Overall_Material           1459 non-null   int64
 16  House_Condition            1459 non-null   int64
 17  Construction_Year          1459 non-null   int64
 18  Remodel_Year               1459 non-null   int64
 19  Roof_Design                1459 non-null   object
 20  Roof_Quality               1459 non-null   object
 21  Exterior1st                1459 non-null   object
 22  Exterior2nd                1459 non-null   object
 23  Brick_Veneer_Type          1451 non-null   object
 24  Brick_Veneer_Area          1451 non-null   float64
 25  Exterior_Material          1459 non-null   object
 26  Exterior_Condition         1459 non-null   object
 27  Foundation_Type            1459 non-null   object
 28  Basement_Height            1422 non-null   object
 29  Basement_Condition         1422 non-null   object
 30  Exposure_Level             1421 non-null   object
 31  BsmtFinType1               1422 non-null   object
 32  BsmtFinSF1                 1459 non-null   int64
 33  BsmtFinType2               1421 non-null   object
 34  BsmtFinSF2                 1459 non-null   int64
 35  BsmtUnfSF                  1459 non-null   int64
 36  Total_Basement_Area        1459 non-null   int64
 37  Heating_Type               1459 non-null   object
 38  Heating_Quality            1459 non-null   object
 39  Air_Conditioning           1459 non-null   object
 40  Electrical_System          1458 non-null   object
 41  First_Floor_Area           1459 non-null   int64
 42  Second_Floor_Area          1459 non-null   int64
 43  LowQualFinSF               1459 non-null   int64
 44  Grade_Living_Area          1459 non-null   int64
 45  Underground_Full_Bathroom  1459 non-null   int64
 46  Underground_Half_Bathroom  1459 non-null   int64
 47  Full_Bathroom_Above_Grade  1459 non-null   int64
 48  Half_Bathroom_Above_Grade  1459 non-null   int64
 49  Bedroom_Above_Grade        1459 non-null   int64
 50  Kitchen_Above_Grade        1459 non-null   int64
 51  Kitchen_Quality            1459 non-null   object
 52  Rooms_Above_Grade          1459 non-null   int64
 53  Functional_Rate            1459 non-null   object
 54  Fireplaces                 1459 non-null   int64
 55  Garage                     1378 non-null   object
 56  Garage_Built_Year          1378 non-null   float64
 57  Garage_Finish_Year         1378 non-null   object
 58  Garage_Size                1459 non-null   int64
 59  Garage_Area                1459 non-null   float64
 60  Garage_Quality             1378 non-null   object
 61  Garage_Condition           1378 non-null   object
 62  Pavedd_Drive               1459 non-null   object
 63  W_Deck_Area                1459 non-null   float64
 64  Open_Lobby_Area            1459 non-null   float64
 65  Enclosed_Lobby_Area        1459 non-null   float64
 66  Three_Season_Lobby_Area    1459 non-null   int64
 67  Screen_Lobby_Area          1459 non-null   int64
 68  Pool_Area                  1459 non-null   int64
 69  Miscellaneous_Value        1459 non-null   int64
 70  Month_Sold                 1459 non-null   int64
 71  Year_Sold                  1459 non-null   int64
 72  Sale_Type                  1459 non-null   object
 73  Sale_Condition             1459 non-null   object
 74  Sale_Price                 1459 non-null   int64
dtypes: float64(7), int64(30), object(38)
memory usage: 866.3+ KB

In [33]:
cat_null_cols = ['Electrical_System', 'Brick_Veneer_Type', 'Basement_Height', 'Basement_Condition',
                 'BsmtFinType1', 'Exposure_Level', 'BsmtFinType2', 'Garage_Condition', 'Garage_Quality',
                 'Garage_Finish_Year', 'Garage']

In [52]:
data.Electrical_System.value_counts()

SBrkr    1333
FuseA    94
FuseF    27
FuseP    3
Mix      1
Name: Electrical_System, dtype: int64

In [53]:
data.Brick_Veneer_Type.value_counts()

None       863
BrkFace    445
Stone      128
BrkCmn     15
Name: Brick_Veneer_Type, dtype: int64

In [54]:
data.Basement_Height.value_counts()

TA    648
Gd    618
Ex    121
Fa    35
Name: Basement_Height, dtype: int64

In [55]:
data.Basement_Condition.value_counts()

TA    1310
Gd    65
Fa    45
Po    2
Name: Basement_Condition, dtype: int64

In [56]:
data.BsmtFinType1.value_counts()

Unf    430
GLQ    418
ALQ    220
BLQ    147
Rec    133
LwQ    74
Name: BsmtFinType1, dtype: int64

In [57]:
data.Exposure_Level.value_counts()

No    952
Av    221
Gd    134
Mn    114
Name: Exposure_Level, dtype: int64

In [58]:
data.BsmtFinType2.value_counts()

Unf    1256
Rec    54
LwQ    45
BLQ    33
ALQ    19
GLQ    14
Name: BsmtFinType2, dtype: int64

In [59]:
data.Garage_Condition.value_counts()

TA    1325
Fa    35
Gd    9
Po    7
Ex    2
Name: Garage_Condition, dtype: int64

In [60]:
data.Garage_Quality.value_counts()

TA    1310
Fa    48
Gd    14
Ex    3
Po    3
Name: Garage_Quality, dtype: int64

In [61]:
data.Garage_Finish_Year.value_counts()

Unf    605
RFn    422
Fin    351
Name: Garage_Finish_Year, dtype: int64

In [62]:
data.Garage.value_counts()

Attchd     869
Detchd     387
BuiltIn    88
Basment    19
CarPort    9
2TFes      5
2Types     1
Name: Garage, dtype: int64

## Imputation

In [63]:
from sklearn.impute import SimpleImputer

In [64]:
cat_imputer = SimpleImputer(strategy='most_frequent')

In [65]:
cat_imputer.fit(data[cat_null_cols])

data[cat_null_cols] = cat_imputer.transform(data[cat_null_cols])

In [67]:
data['Lot_Extent'].mean()

70.04583333333333

In [68]:
data['Brick_Veneer_Area'].mean()

103.75671950379049

In [69]:
data['Garage_Built_Year'].mean()

1978.5159651669085

In [72]:
data['Lot_Extent'] = data['Lot_Extent'].replace(np.nan, 70)

data['Brick_Veneer_Area'] = data['Brick_Veneer_Area'].replace(np.nan, 100)

data['Garage_Built_Year'] = data['Garage_Built_Year'].replace(np.nan, 1978)

In [73]:
data.isnull().sum()

Building_Class               0
Zoning_Class                 0
Lot_Extent                   0
Lot_Size                     0
Road_Type                    0
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Type            0
Brick_Veneer_Area            0
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Height              0
Basement_Condition           0
Exposure_Level               0
BsmtFinType1                 0
BsmtFinSF1                   0
BsmtFinType2                 0
BsmtFinSF2                   0
BsmtUnfSF                    0
Total_Basement_Area          0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            0
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Garage                       0
Garage_Built_Year            0
Garage_Finish_Year           0
Garage_Size                  0
Garage_Area                  0
Garage_Quality               0
Garage_Condition             0
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [75]:
data[data.select_dtypes(include = ['object']).columns] = data[data.select_dtypes(include = ['object']).columns].apply(le.fit_transform)

In [76]:
data.head()

    Building_Class  Zoning_Class  Lot_Extent  Lot_Size  Road_Type  Property_Shape  Land_Outline  Utility_Type  Lot_Configuration  Property_Slope  Neighborhood  Condition1  Condition2  House_Type  House_Design  Overall_Material  House_Condition  Construction_Year  Remodel_Year  Roof_Design  Roof_Quality  Exterior1st  Exterior2nd  Brick_Veneer_Type  Brick_Veneer_Area  Exterior_Material  Exterior_Condition  Foundation_Type  Basement_Height  Basement_Condition  Exposure_Level  BsmtFinType1  BsmtFinSF1  BsmtFinType2  BsmtFinSF2  BsmtUnfSF  Total_Basement_Area  Heating_Type  Heating_Quality  Air_Conditioning  Electrical_System  First_Floor_Area  Second_Floor_Area  LowQualFinSF  Grade_Living_Area  Underground_Full_Bathroom  Underground_Half_Bathroom  Full_Bathroom_Above_Grade  Half_Bathroom_Above_Grade  Bedroom_Above_Grade  Kitchen_Above_Grade  Kitchen_Quality  Rooms_Above_Grade  Functional_Rate  Fireplaces  Garage  Garage_Built_Year  Garage_Finish_Year  Garage_Size  Garage_Area  Garage_Quality  Garage_Condition  Pavedd_Drive  W_Deck_Area  Open_Lobby_Area  Enclosed_Lobby_Area  Three_Season_Lobby_Area  Screen_Lobby_Area  Pool_Area  Miscellaneous_Value  Month_Sold  Year_Sold  Sale_Type  Sale_Condition  Sale_Price
Id
1   60              3             65.0        8450      1          3               3             0             4                  0               5             2           2           0           5             7                 5                2003               2003          1            4             12           13           1                  196.0              2                  4                   2                2                3                   3               2             706         5             0           150        856                  1             0                1                 4                  856               854                0             1710               1                          0                          2                          1                          3                    1                    2                8                  7                0           2       2003.0             1                   2            1085.793744  4               4                 2             163.788080   69.596115        20.337934            0                        0                  0          0                    2           2008       8          4               208500
2   20              3             80.0        9600      1          3               3             0             2                  0               24            1           2           0           2             6                 8                1976               1976          1            4             8            8            2                  0.0                3                  4                   1                2                3                   1               0             978         5             0           284        1262                 1             0                1                 4                  1262              0                  0             1262               0                          1                          2                          0                          3                    1                    3                6                  7                1           2       1976.0             1                   2            196.316304   4               4                 2             198.900074   74.716033        15.039392            0                        0                  0          0                    5           2007       8          4               181500
3   60              3             68.0        11250     1          0               3             0             4                  0               5             2           2           0           5             7                 5                2001               2002          1            4             12           13           1                  162.0              2                  4                   2                2                3                   2               2             486         5             0           434        920                  1             0                1                 4                  920               866                0             1786               1                          0                          2                          1                          3                    1                    2                6                  7                1           2       2001.0             1                   2            218.068403   4               4                 2             26.127533    32.085268       -46.232198            0                        0                  0          0                    9           2008       8          4               223500
4   70              3             60.0        9550      1          0               3             0             0                  0               6             2           2           0           5             7                 5                1915               1970          1            4             13           15           2                  0.0                3                  4                   0                3                1                   3               0             216         5             0           540        756                  1             2                1                 4                  961               756                0             1717               1                          0                          1                          0                          3                    1                    2                7                  7                1           6       1998.0             2                   3            696.996439   4               4                 2             46.948018    40.181415        60.921821            0                        0                  0          0                    2           2006       8          0               140000
5   60              3             84.0        14260     1          0               3             0             2                  0               15            2           2           0           5             8                 5                2000               2000          1            4             12           13           1                  350.0              2                  4                   2                2                3                   0               2             655         5             0           490        1145                 1             0                1                 4                  1145              1053               0             2198               1                          0                          2                          1                          4                    1                    2                9                  7                1           2       2000.0             1                   3            568.859882   4               4                 2            -10.626105    20.755323        21.788818            0                        0                  0          0                    12          2008       8          4               250000

## Train-Validation Split

In [77]:
from sklearn.model_selection import train_test_split

train, valid = train_test_split(data, test_size = 0.3, random_state = 123)

In [78]:
print("Shape of training set:", train.shape)
print("Shape of validation set:", valid.shape)

Shape of training set: (1021, 75)
Shape of validation set: (438, 75)

In [79]:
x_train = train.drop('Sale_Price', axis = 1)
y_train = train['Sale_Price']

x_valid = valid.drop('Sale_Price', axis = 1)
y_valid = valid['Sale_Price']

In [80]:
print(x_train.shape)

print(x_valid.shape)

(1021, 74)
(438, 74)

## Model Building

In [81]:
from sklearn.linear_model import LinearRegression

LR = LinearRegression()

LR.fit(x_train, y_train)

pred_train = LR.predict(x_train)
pred_valid = LR.predict(x_valid)

Rsquare = LR.score(x_train, y_train)
Rsquare

0.8470099664059669

In [87]:
from sklearn import metrics

In [90]:
print('Train RMSE:',np.sqrt(metrics.mean_squared_error(y_train, pred_train)))
print('Validation RMSE:',np.sqrt(metrics.mean_squared_error(y_valid, pred_valid)))

Train RMSE: 82908.12152973685
Validation RMSE: 80328.0102208276

In [89]:
metrics.mean_squared_error(y_train, pred_train)

6873756615.589614

## Model Improvement

## Feature Scaling

In [91]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train_sc = sc.fit_transform(x_train)
x_valid_sc = sc.transform(x_valid)

In [93]:
x_train_sc[0]

array([ 0.65383797, -0.06396467, -0.57850067, -0.1514597 ,  0.07015169,
       -1.43063263,  0.32452979, -0.03131121, -1.25564979, -0.2158686 ,
       -1.21188451, -0.05264042, -0.04134428, -0.4227074 ,  1.56174569,
       -0.7593884 , -0.5148861 ,  0.84418079,  0.54203405, -0.49454756,
       -0.0601593 ,  0.73027941,  0.73918977,  0.41796299, -0.57263644,
       -0.74221895,  0.3584537 ,  0.78197466, -0.31906752,  0.28197839,
       -2.08536417, -0.42635754, -0.30426723,  0.29396713, -0.27756614,
        0.01327459, -0.39969424, -0.11689809, -0.88537338,  0.26921923,
        0.31447544, -0.62306332, -0.79680019, -0.12946482, -1.11587204,
       -0.80010956, -0.23415494, -1.02012268, -0.74086771, -1.0420921 ,
       -0.22929745,  0.78757216, -0.92115363,  0.26345974, -0.95241139,
        1.55481858,  0.82986205,  0.9309808 ,  0.33330119,  0.38090652,
        0.22650844,  0.18691072,  0.31140245, -1.38094727,  0.73205228,
        1.04575077, -0.10857774, -0.26908836, -0.06922681, -0.1088081 ,
        0.24198596, -1.38272247,  0.31711024,  0.22038104])

In [94]:
LR = LinearRegression()

LR.fit(x_train_sc, y_train)

pred_train = LR.predict(x_train_sc)
pred_valid = LR.predict(x_valid_sc)

Rsquare = LR.score(x_train_sc, y_train)
Rsquare

0.8470095800759213

Here are three common evaluation metrics for regression problems:

**Mean Absolute Error** (MAE) is the mean of the absolute value of the errors:
 
**Mean Squared Error** (MSE) is the mean of the squared errors:
 
**Root Mean Squared Error** (RMSE) is the square root of the mean of the squared errors:

 
Comparing these metrics:

- **MAE** is the easiest to understand, because it's the average error.
- **MSE** is more popular than MAE, because MSE "punishes" larger errors, which tends to be useful in the real world.
- **RMSE** is even more popular than MSE, because RMSE is interpretable in the "y" units.

All of these are loss functions, because we want to minimize them.

We will be using **RMSE** loss function to evaluate our predictions.

In [95]:
print('Train RMSE:',np.sqrt(metrics.mean_squared_error(y_train, pred_train)))
print('Validation RMSE:',np.sqrt(metrics.mean_squared_error(y_valid, pred_valid)))

Train RMSE: 31519.676927849792
Validation RMSE: 28155.07905357184

By using **Standard Scaler** method we were able to reduce **RMSE** by **50,000** units approx.